In [ ]:
# Weight = 100 pounds / 45 kgs
# Height = 61 inches / 1.4945 m

In [11]:
print(61*0.0245)
print(100*0.45)

1.4945000000000002
45.0


In [7]:
45/(1.4945*1.4945)

20.14747729519222

In [2]:
#Broadcasting of array elements for arithmetics

#Calculate BMI of cricket
import numpy as np
#Heights of the players in inches 
height_inches = [61,65,63,69,70,73,68,64,63,62,66]

#Convert this to numpy array
ht_np = np.array(height_inches)
# ht_np
#Convert height from inch to meters by exposing it to 0.0245
ht_np = ht_np * 0.0245
ht_np

array([1.4945, 1.5925, 1.5435, 1.6905, 1.715 , 1.7885, 1.666 , 1.568 ,
       1.5435, 1.519 , 1.617 ])

In [3]:
#Weight of players in pounds
weight_pounds = [100,200,160,180,140,155,165,172,180,200,168]

#Convert this to numpy array
wt_np = np.array(weight_pounds)

#Convert weight from pounds to kgs by exposing it to 0.45
wt_np = wt_np * 0.45
wt_np

array([45.  , 90.  , 72.  , 81.  , 63.  , 69.75, 74.25, 77.4 , 81.  ,
       90.  , 75.6 ])

In [4]:
#BMI Calculation
# formula - bmi = weight in kgs / (height in meters ** 2)
bmi = wt_np / (ht_np ** 2)
bmi

array([20.1474773 , 35.48817184, 30.22172356, 28.3435777 , 21.41964658,
       21.80551373, 26.75139684, 31.48102353, 33.99943901, 39.0055999 ,
       28.91357251])

In [5]:
#Boolean based subsetting - try to get players with BMI less than 21
bmi[bmi < 21]

array([20.1474773])